name: gpt-pull-bot
description: A GitHub Action that automatically comments on pull requests using chat gpt-3
author:  Hasan Ozdemir
branding:
    icon: award
    color: blue
inputs:
    api-key:
        description: "API key for GPT-3"
        required: true
    github-token:
        description: "GitHub Token"
        required: true
    model:
        description: "GPT-3 model to use"
        required: false
        default: gpt-3.5-turbo
    review-focus:
        description: "Focus of the review"
        required: false
        default: syntax
runs:
    using: 'node16'
    main:  "dist/index.js"
